### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by salwator** [abatilo/actions-poetry#2]
Could you please consider supporting official 3.8 python version?
Would be great to be possible to use this useful github action for projects that moved to newest version.

**Comment by abatilo** [comment]
Please note that I've switched to using tags correctly for releases of this action, so the version of this action that uses 3.8 is `v1.0.0`. I've had other versions that were tagged without the `v` and I'm going to stop using that scheme but I don't want to remove anything as to not break any other usages of these actions. Moving forward, all releases will be managed by `semantic-release`.

Thank you!
