### ISSUE TITLE
Installation error with Python 3.5 and `ubuntu-latest`

### ISSUE THREAD

**Issue by thejcannon** [abatilo/actions-poetry#32]
Using:

```yml
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Poetry Metadata
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.5.0
          poetry_version: 1.0
          args: check
```

I see:
```sh
Latest version is '3.5.0'
Downloading Python-3.5.0.tar.xz...
-> https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tar.xz
Installing Python-3.5.0...
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems
```

Here's the relevant part of the link: https://github.com/pyenv/pyenv/wiki/Common-build-problems#error-the-python-ssl-extension-was-not-compiled-missing-the-openssl-lib

**Comment by thejcannon** [comment]
Using version 3.5.8 fixed this, so it's a pretty low-priority thing (as I probably should've been using the latest update version to begin with)

**Comment by abatilo** [comment]
I'm going to close this since it appears that using a newer version solves the problem. I'm not sure how important it is to support an older patch version.
