### ISSUE TITLE
Addition of major version tags

### ISSUE THREAD

**Issue by noritada** [abatilo/actions-poetry#51]
Thank you very much for this nice Action.

It would be great if you could add major version tags so that major releases always refer to the latest patch release. That way users would be able to keep using `uses: abatilo/actions-poetry@v2` for the latest version of this Action, instead of rewriting `uses: abatilo/actions-poetry@v2.1.5` to `uses: abatilo/actions-poetry@v2.1.6` for example. Since this Action employs semantic versioning, users would not be inconvenienced by the use of major version tags.

### Concerns

Major version tag replacement may need to be a manual operation documented in [action-versioning.md](https://github.com/actions/toolkit/blob/main/docs/action-versioning.md) for the time being.

It seems that `actions/setup-python` and other GitHub official Actions are using a workflow [release-new-action-version.yml](https://github.com/actions/setup-python/blob/main/.github/workflows/release-new-action-version.yml) to replace a major version tag when adding a patch version tag to make a patch release. However, that workflow is implemented using [`actions/publish-action`](https://github.com/actions/publish-action), which is still in an alpha version and is only used internally on GitHub, so it does not seem possible at this time for a third party to use it to implement the major version tag replacement.

**Comment by abatilo** [comment]
https://github.com/abatilo/actions-poetry/commit/7f129acb953ae03fdd54c858be5500950f866421

A little crude but I think this should do what you're looking for @noritada! It's not an official release but I do believe you can reference actions from repos using just a raw tag ref.

If you agree, could you go ahead and close this?

**Comment by noritada** [comment]
@abatilo Thank you very much for making major version tags available! I will close this issue.

**Comment by sulunemre** [comment]
"Dependency groups" is a new feature in Poetry, added in version 1.2
To use the latest version, you need to specify it in the workflow file:
```
- name: Install poetry
  uses: abatilo/actions-poetry@v2
  with:
    poetry-version: 1.2
```
