### ISSUE TITLE
Request: supporting latest `main` branch commit

### ISSUE THREAD

**Issue by jamesbraza** [abatilo/actions-poetry#74]
Would you be open to supporting something like `'main'` for `poetry-version`, which would install the latest `main` branch Poetry commit?

**Comment by abatilo** [comment]
Hi @jamesbraza. This just got implemented in #75. Could you take a look and if it works how you wanted, please close this issue.

**Comment by jamesbraza** [comment]
Yeah that PR looks great, thanks. I will close this out 👍
